title: Alec Naidoo
logo: /assets/img/headshot.jpeg
description: +5 years experience as Senior Data Expert in AdTech Industry | Master's in Information and Data Science Candidate | University of California, Berkeley
#show_downloads: true
theme: jekyll-theme-minimal
